### ISSUE TITLE
Fileformats supported by extension not configurable

### ISSUE THREAD

**Issue by cybercamphackathon** [0xddom/atpr#2]
See https://github.com/KuroAku/atpr/blob/master/ATPR.Utils/FilesUtils.cs#L16

Will be nice to be able to configure, list or change this list of supported extensions.

Also, for forensics is usually good to not relay on filenames, so having an option to detect file format by magic will be good

**Comment by 0xddom** [comment]
Ongoing support for magic number detection is on branch `magic`

As of 14:16:
- MimeDetective project (https://github.com/Muraad/Mime-Detective) added to the .sln
- Fix the detection to a less naive approach.

**Comment by 0xddom** [comment]
-Support for extesibility of supported extensions and extraction by strategy pattern
-Extension inference by magic number detection.

Everything merged to master
