### ISSUE TITLE
Spanish language hardcoded

### ISSUE THREAD

**Issue by cybercamphackathon** [0xddom/atpr#3]
Make this configurable (StandfordEnv.cs)

**Comment by 0xddom** [comment]
Added language option in command line. Now the stanford libs are loaded depending of the arguments

**Comment by cybercamphackathon** [comment]
If you make a commit with the message "Fix #numberofissue - description" it will automatically close and associate the commit with the issue. if it's done, please close the issue

**Comment by 0xddom** [comment]
We didn't knew that feature. The changes are already commited to master so I'm closing the issue

**Comment by cybercamphackathon** [comment]
github magic 🙌
